name: secret_vault
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^3.0.0
  local_auth_android: ^2.0.4
  local_auth_darwin: ^2.0.1
  path_provider: ^2.1.5
  pointycastle: any
  encrypt: ^5.0.0-beta.1
  lottie: ^3.3.2

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: exo2
      fonts:
        - asset: assets/fonts/Exo2-Regular.otf
          weight: 400
